"""Script to generate sample course documents for ESI StudyMate testing."""

from pathlib import Path

SAMPLE_OS_TEXT_P1 = """Higher National School of Computer Science (ESI)
Module: Operating Systems & Architecture (Course 302)
Chapter 3: Interrupts and I/O Architecture

1. Definition of Interrupt:
An interrupt is an asynchronous signal sent by hardware or software to the CPU indicating an event that needs immediate attention.
When an interrupt is triggered, the CPU temporarily suspends its current execution sequence, saves the program counter (PC) and processor status flags onto the kernel stack, and transfers execution to a specialized handler known as an Interrupt Service Routine (ISR).

2. Interrupt Types:
- Hardware Interrupts (Asynchronous): Generated by external I/O devices (e.g., keyboard keystroke, disk transfer completion, timer tick).
- Software Interrupts / Traps (Synchronous): Generated by software instructions, such as system calls (syscalls) or exceptions (divide-by-zero, page faults).

3. Interrupt Vector Table (IVT):
The Interrupt Vector Table is an array of memory addresses located in protected kernel memory. Each entry in the table holds the entry-point address of the corresponding ISR for a given interrupt vector number.
"""

SAMPLE_OS_TEXT_P2 = """Chapter 4: Virtual Memory Management and Paging

1. Virtual Memory Definition:
Virtual memory is a memory management capability of an operating system that uses hardware and software to allow a computer to compensate for physical memory shortages by temporarily transferring data from random access memory (RAM) to disk storage.

2. Paging Mechanism:
Physical memory is divided into fixed-size contiguous blocks called frames (or page frames). Logical address space is divided into blocks of the same size called pages.
When a process executes, its pages are mapped into available physical memory frames using a per-process Page Table.
- Typical page size: 4 KB (4096 bytes).
- Address translation: Virtual Address = (Page Number, Offset). The Memory Management Unit (MMU) uses the Page Table Base Register (PTBR) and Translation Lookaside Buffer (TLB) for fast hardware translation.

3. Calculation Examples:
- For a 32-bit virtual address space with 4 KB page size:
  Number of pages = 2^32 / 4096 = 1,048,576 pages (approx 1 Million pages).
- Memory blocks allocation:
  If a file requires 2500 bytes and block size is 512 bytes, the number of required blocks is ceil(2500 / 512) = 5 blocks.
"""


def create_sample_documents():
    data_dir = Path("./data/documents")
    data_dir.mkdir(parents=True, exist_ok=True)

    # Save Chapter 3
    ch3_path = data_dir / "Operating_Systems_Chapter3.txt"
    with open(ch3_path, "w", encoding="utf-8") as f:
        f.write(SAMPLE_OS_TEXT_P1)

    # Save Chapter 4
    ch4_path = data_dir / "Operating_Systems_Chapter4.txt"
    with open(ch4_path, "w", encoding="utf-8") as f:
        f.write(SAMPLE_OS_TEXT_P2)

    return ch3_path, ch4_path


if __name__ == "__main__":
    create_sample_documents()
    print("Sample course documents created successfully in data/documents/.")
